Start to run Python Script
upload failed: ./cus_id.json to s3://week3-mysql-project/input/cus_id.json An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
{'api': {'api_url': 'https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add'}, 's3': {'bucket': 'week3-mysql-project', 'folder': 'input'}, 'db': {'host': 'cth5o34gqq1v.us-east-2.rds.amazonaws.com', 'port': 3306, 'database': 'database-1', 'schema': 'superstore'}, 'run': {'py_script': 'run.py'}}
Traceback (most recent call last):
  File "/home/ubuntu/week3_mysql_project/run.py", line 53, in <module>
    ß
NameError: name 'ß' is not defined
PYTHON RUNNING FAILED
[ERROR:] RETURN CODE:  1
[ERROR:] REFER TO THE LOG FOR THE REASON FOR THE FAILURE.
